# Generated by Django 6.0 on 2026-01-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Technical', 'Technical'), ('Billing', 'Billing'), ('General', 'General')], default='General', max_length=20),
        ),
    ]
